# Jira Configuration
JIRA_URL = "your-jira-url"
JIRA_USERNAME = "your-jira-username"
JIRA_API_TOKEN = "your-jira-api-token"

# Email Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "your-email@gmail.com"
SMTP_PASSWORD = "your-app-specific-password"
SENDER_EMAIL = "your-email@gmail.com" 