[JIRA]
url = "https://your-jira-instance.com"
email = "your-email@example.com"
token = "your-api-token"

[SMTP]
server = "smtp.example.com"
port = 587
username = "your-email@example.com"
password = "your-app-password"
sender_email = "your-email@example.com" 